# Generated by Django 6.0.3 on 2026-03-08 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BaselineClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=128)),
                ("is_spellcaster", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BaselineSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BaselineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("gear", "Gear"),
                            ("tool", "Tool"),
                        ],
                        default="gear",
                        max_length=16,
                    ),
                ),
                (
                    "suggested_for_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suggested_baseline_items",
                        to="core.baselineclass",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BaselineSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=128)),
                ("level", models.PositiveSmallIntegerField()),
                ("school", models.CharField(blank=True, max_length=64)),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="baseline_spells",
                        to="core.baselineclass",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorldClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=128)),
                ("is_spellcaster", models.BooleanField(default=False)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_classes",
                        to="core.world",
                    ),
                ),
            ],
            options={
                "ordering": ["world_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorldClassSpellProgression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_level", models.PositiveSmallIntegerField()),
                ("spell_level", models.PositiveSmallIntegerField()),
                ("slots", models.PositiveSmallIntegerField(default=0)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_spell_progressions",
                        to="core.world",
                    ),
                ),
                (
                    "world_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_progressions",
                        to="core.worldclass",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "world_id",
                    "world_class_id",
                    "character_level",
                    "spell_level",
                ],
            },
        ),
        migrations.CreateModel(
            name="WorldItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("gear", "Gear"),
                            ("tool", "Tool"),
                        ],
                        default="gear",
                        max_length=16,
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_items",
                        to="core.world",
                    ),
                ),
            ],
            options={
                "ordering": ["world_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorldItemClassRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "world_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_items",
                        to="core.worldclass",
                    ),
                ),
                (
                    "world_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_for_classes",
                        to="core.worlditem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorldSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=128)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_species",
                        to="core.world",
                    ),
                ),
            ],
            options={
                "ordering": ["world_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorldSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=128)),
                ("level", models.PositiveSmallIntegerField()),
                ("school", models.CharField(blank=True, max_length=64)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_spells",
                        to="core.world",
                    ),
                ),
            ],
            options={
                "ordering": ["world_id", "level", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorldSpellClassAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "world_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_spells",
                        to="core.worldclass",
                    ),
                ),
                (
                    "world_spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_for_classes",
                        to="core.worldspell",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaselineClassSpellProgression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_level", models.PositiveSmallIntegerField()),
                ("spell_level", models.PositiveSmallIntegerField()),
                ("slots", models.PositiveSmallIntegerField(default=0)),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_spell_progressions",
                        to="core.baselineclass",
                    ),
                ),
            ],
            options={
                "ordering": ["character_class_id", "character_level", "spell_level"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_class", "character_level", "spell_level"),
                        name="uniq_baseline_spell_progression_cell",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorldBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=128)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_backgrounds",
                        to="core.world",
                    ),
                ),
            ],
            options={
                "ordering": ["world_id", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("world", "code"), name="uniq_world_background_code"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="worldclass",
            constraint=models.UniqueConstraint(
                fields=("world", "code"), name="uniq_world_class_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="worldclassspellprogression",
            constraint=models.UniqueConstraint(
                fields=("world", "world_class", "character_level", "spell_level"),
                name="uniq_world_spell_progression_cell",
            ),
        ),
        migrations.AddConstraint(
            model_name="worlditem",
            constraint=models.UniqueConstraint(
                fields=("world", "code"), name="uniq_world_item_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="worlditemclassrecommendation",
            constraint=models.UniqueConstraint(
                fields=("world_item", "world_class"),
                name="uniq_world_item_class_recommendation",
            ),
        ),
        migrations.AddConstraint(
            model_name="worldspecies",
            constraint=models.UniqueConstraint(
                fields=("world", "code"), name="uniq_world_species_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="worldspell",
            constraint=models.UniqueConstraint(
                fields=("world", "code"), name="uniq_world_spell_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="worldspellclassavailability",
            constraint=models.UniqueConstraint(
                fields=("world_spell", "world_class"),
                name="uniq_world_spell_class_availability",
            ),
        ),
    ]
