# Generated by Django 6.0.3 on 2026-03-08 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_baselinebackground_baselineclass_baselinespecies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="world",
            name="rules_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="worlds",
                to="core.rulessystem",
            ),
        ),
    ]
